Diner99/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Diner99.Models;
using Diner99.Helpers;

namespace Diner99.Pages
{
    public class CartModel : PageModel
    {
        public List<Item> cart { get; set; }
        public double Total { get; set; }

        private readonly Diner99.Data.DishContext _context;

        public CartModel(Diner99.Data.DishContext context)
        {
            _context = context;
        }

        public void OnGet()
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            Total = (double)cart.Sum(i => i.Cusine.Price * i.Quantity);
        }

        public IActionResult OnGetBuyNow(int id)
        {
            var dish = _context.Dish.Where(a => a.ID == id).Single();
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                cart = new List<Item>();
                cart.Add(new Item
                {
                    Cusine = dish,
                    Quantity = 1
                });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                int index = Exists(cart, id);
                if (index == -1)
                {
                    cart.Add(new Item
                    {
                        Cusine = dish,
                        Quantity = 1
                    });
                }
                else
                {
                    cart[index].Quantity++;
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToPage("Cart");
        }

        public IActionResult OnGetDelete(int id)
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("Cart");
        }

        public IActionResult OnPostUpdate(int[] quantities)
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (var i = 0; i < cart.Count; i++)
            {
                cart[i].Quantity = quantities[i];
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("Cart");
        }

        private int Exists(List<Item> cart, int id)
        {
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].Cusine.ID == id)
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

Diner99/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Diner99.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Diner99/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using Diner99.Models;

namespace Diner99.Pages
{
    public class IndexModel : PageModel
    {
        private readonly Diner99.Data.DishContext _context;

        public IndexModel(Diner99.Data.DishContext context)
        {
            _context = context;
        }

        public IList<Dish> Dish { get; set; }

        public async Task OnGetAsync()
        {
            Dish = await _context.Dish.ToListAsync();
        }
    }
}

Diner99/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Diner99.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Diner99/Pages/Cart.cshtml
@page
@model Diner99.Pages.CartModel
@{
    ViewData["Title"] = "Shopping Cart";
}
<h3>Cart</h3>
<form method="post" asp-page="cart" asp-page-handler="update">
    <table class="table">
        <tr>
            <th>Action</th>
            <th>Id</th>
            <th>Name</th>
            <th>Image</th>
            <th>Price</th>
            <th>Quantity <input type="submit" value="Update" /></th>
            <th>Sub Total</th>
        </tr>
        @foreach (var item in Model.cart)
        {
            <tr>
                <td>
                    <a asp-page="cart" asp-page-handler="delete" asp-route-id="@item.Cusine.ID">Remove</a>
                </td>
                <td>@item.Cusine.ID</td>
                <td>@item.Cusine.Name</td>
                <td><img src="~/Images/@item.Cusine.Image" width="120" height="80" /></td>
                <td>SAR @item.Cusine.Price</td>
                <td><input type="number" name="quantities" value="@item.Quantity" min="1" style="width: 50px;" /></td>
                <td>
                    SAR @(item.Cusine.Price * item.Quantity)
                </td>
            </tr>
        }
        <tr>
            <td colspan="6" align="right">Total</td>
            <td align="center">SAR @Model.Total</td>
        </tr>
    </table>
</form>
<a asp-page="index">Continue Shopping</a>

Diner99/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Diner 99</h1>
    
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Dish[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dish[0].Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dish[0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dish[0].Image)
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Dish)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price) SAR
                </td>
                <td>
                    <img src="~/Images/@item.Image" width="120" height="80" />
                </td>
                <td>
                    <a asp-page="./Cart" asp-page-handler="buynow" asp-route-id="@item.ID">Add to Cart</a>
                </td>
            </tr>
        }
    </tbody>
</table>